name: mdbook deploy to github pages

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download mdbook for Lean
      shell: bash
      run: |
        curl -O --location https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz
        tar xvf mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz && mv mdbook-v0.4.37-x86_64-unknown-linux-gnu mdbook-linux
        ./mdbook-linux/mdbook --help
        ldd ./mdbook-linux/mdbook
    - name: Run mdbook build
      shell: bash
      run: |
        ./mdbook-linux/mdbook build
        rm -rf ./out/.git
        rm -rf ./out/.github
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out

